apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-tkul
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-tkul
    app.kubernetes.io/part-of: load-app-8759d090-b97e-4b5d-9da0-9ca5d889787f
  name: devfile-sample-code-with-quarkus-tkul
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-tkul
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-tkul
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-82-tenant/load-app-8759d090-b97e-4b5d-9da0-9ca5d889787f/devfile-sample-code-with-quarkus-tkul@sha256:fe6d0256b80fa6d78f61074f3c31ea47a4782fa1caa842623f8f87fdb70fc2b3
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
